//DO NOT EDIT THIS SCRIPT
//This script is created by the unity editor to make looking for sound clips faster 

public enum ESpellEnum 
{
	BatSonarElectricity = 0,
	LightningBall = 1,
	LightningCone = 2,
	LightningFloor = 3,
	Spark = 4,
	SummonLightning = 5,
	BatSonarFire = 6,
	CactusFire = 7,
	FireBall = 8,
	FireCone = 9,
	FireLine = 10,
	FireWork = 11,
	Flamethrower = 12,
	ProjectileAOEFire = 13,
	BatSonarNature = 14,
	Boulder = 15,
	CactusNature = 16,
	GrassBall = 17,
	SummonMeteor = 18,
	SummonSwamp = 19,
	SwampBall = 20,
	BatSonar = 21,
	Kunai = 22,
	MagicArrow = 23,
	StarterKnife = 24,
	SwordProjectile = 25,
	PumkingExpolosion = 26,
	BatSonarWater = 27,
	Bubble = 28,
	CactusWater = 29,
	IceLine = 30,
	IceSpike = 31,
	SummonRain = 32,
	SummonSnow = 33,

}
